name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run type checking
      - name: Type check
        run: npm run typecheck --if-present

      # 5. Run tests
      - name: Run tests
        run: npm test --if-present

      # 6. Build project
      - name: Build project
        run: npm run build
